export const newB = [
  { testament: "NOVO", abbreviation: "Lc", name: "Lucas" },
  { testament: "NOVO", abbreviation: "Jo", name: "João" },
  { testament: "NOVO", abbreviation: "At", name: "Atos" },
  { testament: "NOVO", abbreviation: "Rm", name: "Romanos" },
  { testament: "NOVO", abbreviation: "1 Co", name: "1 Coríntios" },
  { testament: "NOVO", abbreviation: "2 Co", name: "2 Coríntios" },
  { testament: "NOVO", abbreviation: "Gl", name: "Gálatas" },
  { testament: "NOVO", abbreviation: "Ef", name: "Efésios" },
  { testament: "NOVO", abbreviation: "Fp", name: "Filipenses" },
  { testament: "NOVO", abbreviation: "Cl", name: "Colossenses" },
  { testament: "NOVO", abbreviation: "1 Ts", name: "1 Tessalonicenses" },
  { testament: "NOVO", abbreviation: "2 Ts", name: "2 Tessalonicenses" },
  { testament: "NOVO", abbreviation: "1 Tm", name: "1 Timóteo" },
  { testament: "NOVO", abbreviation: "2 Tm", name: "2 Timóteo" },
  { testament: "NOVO", abbreviation: "Tt", name: "Tito" },
  { testament: "NOVO", abbreviation: "Fm", name: "Filemom" },
  { testament: "NOVO", abbreviation: "Hb", name: "Hebreus" },
  { testament: "NOVO", abbreviation: "Tg", name: "Tiago" },
  { testament: "NOVO", abbreviation: "1 Pe", name: "1 Pedro" },
  { testament: "NOVO", abbreviation: "2 Pe", name: "2 Pedro" },
  { testament: "NOVO", abbreviation: "1 Jo", name: "1 João" },
  { testament: "NOVO", abbreviation: "2 Jo", name: "2 João" },
  { testament: "NOVO", abbreviation: "3 Jo", name: "3 João" },
  { testament: "NOVO", abbreviation: "Jd", name: "Judas" },
  { testament: "NOVO", abbreviation: "Ap", name: "Apocalipse" },
];
